### ISSUE TITLE
locations and schema

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-assist-client#1]
## add locations

Same as before for hosts and networks so
Get one, all, add, delete, patch
https://github.com/NubeIO/rubix-assist/blob/bb6d536d6b4115fdecc142f23ab66ee8e98a3297/pkg/router/router.go#L93

## Add get schema

`GetLocationSchema()`

https://github.com/NubeIO/rubix-assist/blob/bb6d536d6b4115fdecc142f23ab66ee8e98a3297/controller/locations.go#L8

```
ALL get
http://{{updater_ip}}:{{updater_port}}/api/locations/schema
http://{{updater_ip}}:{{updater_port}}/api/networks/schema
http://{{updater_ip}}:{{updater_port}}/api/hosts/schema
```

**Comment by ryangarato** [comment]
On branch "locations_and_schema"
